version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-container
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
#      - ./conf:/etc/nginx/conf.d
    links:
      - node-server:node-server

  node-server:
    build: .
    command: ./node_modules/.bin/nodemon --debug=5858
    container_name: node-container
    ports:
      - 8080:8080
      - 5858:5858
    volumes:
      - .:/home/sloppylopez
      - nodemodules:/home/sloppylopez/node_modules
      - app:/home/sloppylopez/app
    environment:
      - VIRTUAL_HOST=docker.nginx.node.com
      - VIRTUAL_PORT=8080

volumes:
  app:
  nodemodules: