version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-container
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
#      - ./conf:/etc/nginx/conf.d

  node-server:
    build: .
      container_name: node-container
      ports:
        - 3000:3000
    environment:
      - VIRTUAL_HOST=docker.nginx.node.com
      - VIRTUAL_PORT=3000
volumes:
  nodemodules: