version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-container
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    links:
      - portal:portal

  portal:
    build: .
    container_name: app-container
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST=docker.nginx.node.com